# Create a new project with the basic files in place
# Clone the dependent role repositories
# Initialize the git repository and setup the remote 'origin'
---
- set_fact:
    credentials_dir: "{{ extern_dir }}/credentials/{{ project.name }}"
    data_dir: "{{ extern_dir }}/data/{{ project.name }}"
    template_dir: "{{ prepd_dir }}/templates"

- name: Create project directories
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ credentials_dir }}'
    - '{{ data_dir }}'
    - '{{ project_dir }}'

- name: Create links to external directories for credentials and data
  file:
    src: '{{ item.src }}'
    dest: '{{ project_dir }}/{{ item.dest }}'
    state: link
  with_items:
    - { src: '{{ credentials_dir }}', dest: credentials }
    - { src: '{{ data_dir }}', dest: data }

- name: Copy files
  command: 'cp -a {{ template_dir }}/ops {{ project_dir }}'

- name: Create project.yml
  template:
    src: project.yml.j2
    dest: '{{ target_dir }}/ansible/group_vars/all/project.yml'

- name: Create vault password file
  template:
    src: vault-password.txt.j2
    dest: '{{ credentials_dir }}/vault-password.txt'

- name: Add git
  apt:
    name: git
    state: present
  become: yes

- name: Inialize git repostiory
  command: '{{ item }}'
  args:
    chdir: '{{ target_dir }}'
  with_items:
    - git init
    - 'git remote add origin {{ git_origin }}'

- name: Ignore ssh host check for github.com
  blockinfile:
    create: yes
    dest: '{{ ansible_env.HOME }}/.ssh/config'
    marker: '# {mark} ANSIBLE MANAGED BLOCK (ignore-gh)'
    block: |
      Host github.com
        StrictHostKeyChecking no

- name: Clone dependent roles
  command: 'git submodule add {{ item.repo }} {{ item.location }}'
  args:
    chdir: '{{ target_dir }}'
    creates: '{{ item.location }}'
  with_items:
    - { repo: 'git@github.com:rjayroach/prepd-roles.git', location: 'ansible/community-roles/prepd' }
    - { repo: 'git@github.com:rjayroach/terraplate.git', location: 'ansible/community-roles/terraplate' }
    - { repo: 'git@github.com:rjayroach/terraplate-components.git', location: 'ansible/community-roles/terraplate-components' }

- name: Add files and make first commit
  command: '{{ item }}'
  args:
    chdir: '{{ target_dir }}'
  with_items:
    - git add .
    - git commit -m 'first commit from prepd'
