#!/usr/bin/env ansible-playbook
---
- hosts: dev-servers:&local
  vars_files: ['{{ credentials_file }}']
  tags: config
  tasks:
    - include_role:
        name: prepd/dev-server
        tasks_from: config-local

- hosts: dev-servers
  tags: config
  tasks:
    - include_role:
        name: prepd/dev-server
        tasks_from: config


- hosts: dev-servers:&local
  vars_files: ['{{ credentials_file }}']
  tags: deploy
  tasks:
    - include_role:
        name: prepd/dev-server
        tasks_from: deploy-local

- hosts: dev-servers
  tags: deploy
  tasks:
    - include_role:
        name: prepd/dev-server
        tasks_from: deploy
